// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebcesqupaxnflmfhksmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViY2VzcXVwYXhuZmxtZmhrc21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjAwOTYsImV4cCI6MjA3MzE5NjA5Nn0.63lbZX8MtWW420W9v2C-Lq5N6hVbMViNvXjr3LNL3CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});